language: python

sudo: false
dist: trusty


cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache

matrix:
  include:
    - python: '3.8'
      env: TOXENV="py38-linux"

install:
  - pip install -r requirements.txt
  - pip install tox

script: tox -vv